# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37d2d2934fa04b65772594c25108a8ac6b88271b6442b483eab33449dbbd9ad0e938a55dfd8563c3aacc82ae39e8b993aeb524bb6247486359bb9b6ce205eae5

test:
  secret_key_base: a5a1d58ab5c9365bb357c01ad2c6e46ce0c5fdac9219a46dd6af3e5a8a61d0d8e6bea0258f6aaca707c6a92858d502a5aa4fef1fa58bdc476e6bc8fecd9c5fb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
